# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WIyHBNZEC59j6Ce-8-TVyPMpOEfam1xW

## Import Library
"""

!wget https://raw.githubusercontent.com/saffanaha1/MSNBurr_for_PyMC/main/MSNBurr_distribution.py -O MSNBurr_distribution.py
from MSNBurr_distribution import msnburr as msnburr
import pymc as pm
import numpy as np
import arviz as az

sampler_kwargs = {
    "chains": 4,
    "cores": 4,
    "return_inferencedata": True,
    "random_seed": 42,
}

"""## Simulasi Regresi"""

x1 = np.random.normal(0,1,20000)
x2 = np.random.normal(0,1,20000)
b0 = 0.63
b1 = 0.78
b2 = 0.003
ycap = b0 + b1*x1 + b2*x2
eps1 = np.random.normal(0,1,20000)
eps2 = pm.draw(msnburr.dist(0,1,1), draws=20000)
eps3 = pm.draw(msnburr.dist(0,1,0.1), draws=20000)
eps4 = pm.draw(msnburr.dist(0,1,5), draws=20000)
y = ycap + eps4

with pm.Model() as simulasiregresi:
    sigma = pm.HalfCauchy('sigma',5)
    alpha = pm.Gamma('alpha',2,0.5)
    b0 = pm.Normal('b0',0, 0.5)
    b1 = pm.Normal('b1',0, 0.5)
    b2 = pm.Normal('b2',0, 0.5)

    eps = b0 + b1*x1 + b2*x2

    msnburr('Simulasi Regresi', mu=eps, sigma=sigma, alpha=alpha, observed=y)

with simulasiregresi:
    trace_coba = pm.sample(**sampler_kwargs)

az.plot_trace(trace_coba)
az.summary(trace_coba, round_to=3, hdi_prob=0.95)